---

- debug:
    msg: "-> base only"
  tags: [ print_action ]

- name: Check if circom is already installed
  ansible.builtin.shell: which circom
  register: which_circom
  ignore_errors: true

- name: Print circom installation status
  debug:
    msg: "which circom -> {{ which_circom }}"

- name: Install circom from source
  block:
    - name: Clone circom repository
      ansible.builtin.git:
        repo: https://github.com/iden3/circom.git
        version: v2.1.2
        dest: /tmp/circom

    - name: Build circom from source
      ansible.builtin.shell:
        cmd: cargo build --release
        chdir: /tmp/circom
      environment:
        PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"

    - name: Install circom
      ansible.builtin.shell:
        cmd: cargo install --path circom
        chdir: /tmp/circom
      environment:
        PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"

    - name: Print circom info
      ansible.builtin.shell:
        cmd: circom --version
      environment:
        PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
  when: which_circom is failed