---


- debug:
    msg: "-> base only"
  tags: [ print_action ]

- name: Install base packages
  become: True
  apt:
    pkg:
      - build-essential
      - python3
      - parallel

- block:
    - name: Download rustup installer
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-init.sh

    - name: Install rustup
      ansible.builtin.shell:
        cmd: chmod +x rustup-init.sh && ./rustup-init.sh -y
        chdir: /tmp/

    - name: Check that rustup was installed
      ansible.builtin.shell: cargo --version
      environment:
        PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"